# Site settings
title: What Mona (Over)Thought
email: mona.zsh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  coding, writing, gaming, art, and being human
baseurl: ""
url: "https://www.monazsh.com" # the base hostname & protocol for your site
twitter_username: hazelynutter
github_username:  mona-zsh
highlighter: rouge
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
