# Site settings
title: The Diaries of Mona Zhang (Over)Thinking Things
email: mona.zsh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  fiction, non-fiction, entrepreneurship, tech, and being human
baseurl: ""
url: "http://www.monazsh.com" # the base hostname & protocol for your site
twitter_username: mona_zsh
github_username:  mona-zsh
highlighter: rouge
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
